// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"go-framework/http/internal/dao"
	"go-framework/http/internal/service"
)

// Injectors from wire.go:

func NewUserService() *service.User {
	userdao := dao.NewUserDao()
	user := service.NewUserService(userdao)
	return user
}
