Env = "dev" #环境: dev本地 test测试 pre预发  pro生产
Mode="debug"
Port=8888


[mysqlMaster]
    Host=""
    Password=""
    User=""
    Database=""
    MaxopenConns=10
    MaxidleConns=10

[mysqlSlave]
    Host=""
    Password=""
    User = ""
    Database = ""
    MaxopenConns = 10
    MaxidleConns = 10

[log]
    logLevel="debug"
    logFile="/data/logs/xxx.log"
    logPath=""
    isDebug=1
    maxSize=500
    maxBackups=0
    maxAge=30
    compress=false
    dingUrl="https://oapi.dingtalk.com/robot/send?access_token=65857639ac7c1b01c80224fd6b18e1e0e373f2671f62cae17960dbaed80f193c"